In [1]:
import pandas as pd 
import numpy as np

In [5]:
cars = pd.read_csv('d:/data/usedcars.csv')
cars.head()

   year model  price  mileage   color transmission
0  2011   SEL  21992     7413  Yellow         AUTO
1  2011   SEL  20995    10926    Gray         AUTO
2  2011   SEL  19995     7351  Silver         AUTO
3  2011   SEL  17809    11613    Gray         AUTO
4  2012    SE  17500     8367   White         AUTO

In [15]:
cars.color.value_counts()

color
Black     35
Silver    32
Red       25
Blue      17
Gray      16
White     16
Green      5
Yellow     3
Gold       1
Name: count, dtype: int64

In [27]:
cars.groupby("model").mean(numeric_only=True)[['price','mileage']]

              price       mileage
model
SE     12202.128205  46541.269231
SEL    16109.260870  26238.913043
SES    12694.102041  49089.448980

In [41]:
cars[['price','mileage','model']].groupby('model').describe()

      price                                                                   \
      count          mean          std      min       25%      50%       75%
model
SE     78.0  12202.128205  2773.553342   3800.0  10865.75  12995.0  13994.25
SEL    23.0  16109.260870  2475.443986  10995.0  14733.50  15980.0  16997.50
SES    49.0  12694.102041  3059.196192   6200.0  10815.00  13742.0  14699.00

               mileage                                                         \
           max   count          mean           std     min       25%      50%
model
SE     17500.0    78.0  46541.269231  28298.437900  4867.0  29991.25  38964.5
SEL    21992.0    23.0  26238.913043  15547.098203  7351.0  15305.00  25125.0
SES    16995.0    49.0  49089.448980  26012.583031  9199.0  32655.00  38380.0


           75%       max
model
SE     55124.5  151479.0
SEL    33071.5   78264.0
SES    64055.0  119720.0

In [43]:
cars[['price','mileage','model']].groupby('model').quantile(q=[0.25,0.5,0.75])

               price   mileage
model
SE    0.25  10865.75  29991.25
      0.50  12995.00  38964.50
      0.75  13994.25  55124.50
SEL   0.25  14733.50  15305.00
      0.50  15980.00  25125.00
      0.75  16997.50  33071.50
SES   0.25  10815.00  32655.00
      0.50  13742.00  38380.00
      0.75  14699.00  64055.00

In [47]:
insurance = pd.read_csv('d:/data/insurance.csv')
insurance.shape

(1338, 7)

In [49]:
insurance.head()

   age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [59]:
insurance[['age','bmi','charges','gender']].groupby('gender').mean()

              age        bmi       charges
gender
female  39.436090  30.370211  12575.123638
male    38.980684  30.953098  13957.455827

In [65]:
insurance[['age','bmi','charges','smoker']].groupby('smoker').describe()['age']

         count       mean        std   min    25%   50%   75%   max
smoker
no      1064.0  39.385338  14.083410  18.0  26.75  40.0  52.0  64.0
yes      274.0  38.514599  13.923186  18.0  27.00  38.0  49.0  64.0

In [67]:
insurance[['age','bmi','charges','smoker']].groupby('smoker').describe()['bmi']

         count       mean       std     min       25%      50%    75%    max
smoker
no      1064.0  30.651795  6.043111  15.960  26.31500  30.3525  34.43  53.13
yes      274.0  30.708449  6.318644  17.195  26.08375  30.4475  35.20  52.58

In [69]:
insurance[['age','bmi','charges','smoker']].groupby('smoker').describe()['charges']

,count,mean,std,min,25%,50%,75%,max
smoker,,,,,,,,
no,1064.0,8434.268298,5993.781819,1121.8739,3986.438700,7345.40530,11362.887050,36910.60803
yes,274.0,32050.231832,11541.547176,12829.4551,20826.244213,34456.34845,41019.207275,63770.42801

In [71]:
credit = pd.read_csv('d:/data/credit.csv')
credit.shape

(1000, 21)

In [73]:
credit.head()

,checking_balance,months_loan_duration,credit_history,purpose,amount,savings_balance,employment_length,installment_rate,personal_status,other_debtors,...,property,age,installment_plan,housing,existing_credits,default,dependents,telephone,foreign_worker,job
0,< 0 DM,6,critical,radio/tv,1169,unknown,> 7 yrs,4,single male,none,...,real estate,67,none,own,2,1,1,yes,yes,skilled employee
1,1 - 200 DM,48,repaid,radio/tv,5951,< 100 DM,1 - 4 yrs,2,female,none,...,real estate,22,none,own,1,2,1,none,yes,skilled employee
2,unknown,12,critical,education,2096,< 100 DM,4 - 7 yrs,2,single male,none,...,real estate,49,none,own,1,1,2,none,yes,unskilled resident
3,< 0 DM,42,repaid,furniture,7882,< 100 DM,4 - 7 yrs,2,single male,guarantor,...,building society savings,45,none,for free,1,1,2,none,yes,skilled employee
4,< 0 DM,24,delayed,car (new),4870,< 100 DM,1 - 4 yrs,3,single male,none,...,unknown/none,53,none,for free,2,2,2,none,yes,skilled employee

In [77]:
credit[['purpose','amount']].groupby('purpose').mean()

                          amount
purpose
business             4158.041237
car (new)            3063.025641
car (used)           5370.223301
domestic appliances  1498.000000
education            3180.400000
furniture            3066.988950
others               8209.333333
radio/tv             2487.653571
repairs              2728.090909
retraining           1205.888889

In [91]:
cars.groupby(['model','color']).mean(numeric_only=True)

                     year         price        mileage
model color
SE    Black   2009.578947  13345.210526   34167.421053
      Blue    2009.222222  13196.444444   35695.000000
      Gold    2009.000000  10955.000000   40180.000000
      Gray    2009.142857  12816.571429   40932.000000
      Green   2007.000000  10900.000000   40483.500000
      Red     2006.666667  10829.083333   65958.083333
      Silver  2008.000000  11444.818182   50097.363636
      White   2009.142857  12459.071429   48364.142857
      Yellow  2001.000000   4899.000000  151479.000000
SEL   Black   2010.333333  15290.333333   25634.666667
      Blue    2010.333333  16226.666667   19691.333333
      Gray    2010.000000  15592.600000   33175.600000
      Green   2011.000000  16950.000000    9388.000000
      Red     2009.000000  13969.500000   39381.500000
      Silver  2010.000000  16448.285714   23733.142857
      White   2010.000000  15980.000000   39943.000000
      Yellow  2011.000000  21992.000000    7413.000000
SES   Black   2008.538462  12814.538462   49681.923077
      Blue    2008.400000  13058.400000   38744.000000
      Gray    2008.500000  12742.250000   46586.000000
      Red     2008.000000  11689.272727   54966.636364
      Silver  2009.214286  13905.714286   42658.928571
      White   2003.000000   7900.000000   96000.000000
      Yellow  2007.000000   7999.000000   81596.000000

In [95]:
df1 = credit[['purpose','personal_status','amount']].groupby(['purpose','personal_status']).describe()
df1

                                    amount                             \
                                     count          mean          std
purpose             personal_status
business            divorced male     10.0   4142.700000  2840.912179
                    female            19.0   3195.421053  2428.716037
                    married male       9.0   2323.444444  1777.269050
                    single male       59.0   4750.491525  3547.188694
car (new)           divorced male     10.0   2843.800000  2393.082986
                    female            70.0   2531.557143  2239.280627
                    married male      20.0   1632.050000  1209.099512
                    single male      134.0   3570.597015  3385.133320
car (used)          divorced male      3.0   6534.000000  2710.602701
                    female            24.0   5814.375000  3375.829442
                    married male       6.0   4743.333333  3012.105089
                    single male       70.0   5221.800000  2738.925107
domestic appliances divorced male      1.0   1338.000000          NaN
                    female             6.0   1409.833333  1309.827991
                    married male       1.0   1217.000000          NaN
                    single male        4.0   1740.500000   877.930331
education           divorced male      1.0   2319.000000          NaN
                    female            21.0   2187.809524  2313.955890
                    married male       1.0   3711.000000          NaN
                    single male       27.0   3964.666667  3401.822939
furniture           divorced male     15.0   3082.066667  1535.245465
                    female            74.0   2774.729730  2039.363151
                    married male       7.0   2252.142857   904.503442
                    single male       85.0   3385.870588  2137.160743
others              divorced male      1.0  15857.000000          NaN
                    female             3.0  11653.666667  8763.774434
                    single male        8.0   5961.750000  4190.446712
radio/tv            divorced male      7.0   2138.142857   826.963407
                    female            85.0   2400.517647  1886.589930
                    married male      42.0   1920.976190  1593.566555
                    single male      146.0   2718.157534  2304.143679
repairs             divorced male      2.0   7028.000000  7028.641405
                    female             5.0   2126.400000  1171.540140
                    married male       3.0    875.333333   560.907598
                    single male       12.0   2725.333333  1915.722951
retraining          female             3.0   1757.666667  1463.128953
                    married male       3.0    726.000000   335.608403
                    single male        3.0   1134.000000   340.141147

                                                                           \
                                         min       25%      50%       75%
purpose             personal_status
business            divorced male     1275.0   1986.75   3340.5   5830.50
                    female             609.0   1300.00   2528.0   4294.00
                    married male       907.0   1391.00   1887.0   2169.00
                    single male       1037.0   2350.50   3844.0   6023.00
car (new)           divorced male      640.0   1335.25   2359.5   3318.75
                    female             250.0   1219.00   1483.5   3073.00
                    married male       276.0    929.25   1256.5   1885.00
                    single male        571.0   1321.00   2245.0   3997.75
car (used)          divorced male     3857.0   5162.50   6468.0   7872.50
                    female            1352.0   3567.50   4743.0   7553.25
                    married male      1503.0   2528.50   4463.5   6177.25
                    single male       1236.0   2913.50   4737.0   7446.50
domestic appliances divorced male     1338.0   1338.00   1338.0   1338.00
                    female             343.0    774.25   1055.0   1265.25
                    married male      1217.0   1217.00   1217.0   1217.00
                    single male       1225.0   1252.75   1343.0   1830.75
education           divorced male     2319.0   2319.00   2319.0   2319.00
                    female             392.0   1047.00   1501.0   1927.00
                    married male      3711.0   3711.00   3711.0   3711.00
                    single male        684.0   1316.00   2273.0   6167.00
furniture           divorced male      975.0   1951.00   3021.0   3918.50
                    female             428.0   1407.50   2166.0   3559.50
                    married male      1221.0   1649.50   2069.0   2672.00
                    single male        708.0   1984.00   2828.0   3976.00
others              divorced male    15857.0  15857.00  15857.0  15857.00
                    female            1755.0   8268.50  14782.0  16603.00
                    single male       1164.0   2311.25   5847.5   8518.50
radio/tv            divorced male     1126.0   1548.00   2149.0   2680.50
                    female             385.0   1240.00   1715.0   2991.00
                    married male       426.0   1031.25   1443.0   2057.00
                    single male        338.0   1346.25   2109.0   3098.00
repairs             divorced male     2058.0   4543.00   7028.0   9513.00
                    female             996.0   1190.00   1943.0   2631.00
                    married male       454.0    557.00    660.0   1086.00
                    single male        639.0   1303.00   1969.5   3843.00
retraining          female             894.0    913.00    932.0   2189.50
                    married male       339.0    620.50    902.0    919.50
                    single male        754.0    996.00   1238.0   1324.00


                                         max
purpose             personal_status
business            divorced male     9572.0
                    female            8318.0
                    married male      6568.0
                    single male      15945.0
car (new)           divorced male     8978.0
                    female           10722.0
                    married male      5234.0
                    single male      14896.0
car (used)          divorced male     9277.0
                    female           12976.0
                    married male      9398.0
                    single male      11054.0
domestic appliances divorced male     1338.0
                    female            3990.0
                    married male      1217.0
                    single male       3051.0
education           divorced male     2319.0
                    female            8471.0
                    married male      3711.0
                    single male      12612.0
furniture           divorced male     6872.0
                    female           10974.0
                    married male      3832.0
                    single male      14179.0
others              divorced male    15857.0
                    female           18424.0
                    single male      11938.0
radio/tv            divorced male     3235.0
                    female           10144.0
                    married male      7166.0
                    single male      15653.0
repairs             divorced male    11998.0
                    female            3872.0
                    married male      1512.0
                    single male       6204.0
retraining          female            3447.0
                    married male       937.0
                    single male       1410.0

In [97]:
df1.loc['business']

                amount                                                     \
                 count         mean          std     min      25%     50%
personal_status
divorced male     10.0  4142.700000  2840.912179  1275.0  1986.75  3340.5
female            19.0  3195.421053  2428.716037   609.0  1300.00  2528.0
married male       9.0  2323.444444  1777.269050   907.0  1391.00  1887.0
single male       59.0  4750.491525  3547.188694  1037.0  2350.50  3844.0


                    75%      max
personal_status
divorced male    5830.5   9572.0
female           4294.0   8318.0
married male     2169.0   6568.0
single male      6023.0  15945.0

In [101]:
df1.loc['radio/tv']

                amount                                                     \
                 count         mean          std     min      25%     50%
personal_status
divorced male      7.0  2138.142857   826.963407  1126.0  1548.00  2149.0
female            85.0  2400.517647  1886.589930   385.0  1240.00  1715.0
married male      42.0  1920.976190  1593.566555   426.0  1031.25  1443.0
single male      146.0  2718.157534  2304.143679   338.0  1346.25  2109.0


                    75%      max
personal_status
divorced male    2680.5   3235.0
female           2991.0  10144.0
married male     2057.0   7166.0
single male      3098.0  15653.0

In [103]:
credit.purpose.value_counts()

purpose
radio/tv               280
car (new)              234
furniture              181
car (used)             103
business                97
education               50
repairs                 22
domestic appliances     12
others                  12
retraining               9
Name: count, dtype: int64

In [111]:
cars[['model','price','mileage']].groupby('model').describe()

      price                                                                   \
      count          mean          std      min       25%      50%       75%
model
SE     78.0  12202.128205  2773.553342   3800.0  10865.75  12995.0  13994.25
SEL    23.0  16109.260870  2475.443986  10995.0  14733.50  15980.0  16997.50
SES    49.0  12694.102041  3059.196192   6200.0  10815.00  13742.0  14699.00

               mileage                                                         \
           max   count          mean           std     min       25%      50%
model
SE     17500.0    78.0  46541.269231  28298.437900  4867.0  29991.25  38964.5
SEL    21992.0    23.0  26238.913043  15547.098203  7351.0  15305.00  25125.0
SES    16995.0    49.0  49089.448980  26012.583031  9199.0  32655.00  38380.0


           75%       max
model
SE     55124.5  151479.0
SEL    33071.5   78264.0
SES    64055.0  119720.0

In [ ]:
cars.pivot_table