In [1]:
import pandas as pd

In [3]:
cars = pd.read_csv('d:/data/usedcars.csv')
cars.head()

   year model  price  mileage   color transmission
0  2011   SEL  21992     7413  Yellow         AUTO
1  2011   SEL  20995    10926    Gray         AUTO
2  2011   SEL  19995     7351  Silver         AUTO
3  2011   SEL  17809    11613    Gray         AUTO
4  2012    SE  17500     8367   White         AUTO

In [7]:
cars.groupby(['model','color']).size()

model  color
SE     Black     19
       Blue       9
       Gold       1
       Gray       7
       Green      4
       Red       12
       Silver    11
       White     14
       Yellow     1
SEL    Black      3
       Blue       3
       Gray       5
       Green      1
       Red        2
       Silver     7
       White      1
       Yellow     1
SES    Black     13
       Blue       5
       Gray       4
       Red       11
       Silver    14
       White      1
       Yellow     1
dtype: int64

In [39]:
cars.pivot_table(values="price",index="color",columns="model",aggfunc="count",margins=True,margins_name="Grand Total",fill_value=0).transpose()

color,Black,Blue,Gold,Gray,Green,Red,Silver,White,Yellow,Grand Total
model,,,,,,,,,,
SE,19,9,1,7,4,12,11,14,1,78
SEL,3,3,0,5,1,2,7,1,1,23
SES,13,5,0,4,0,11,14,1,1,49
Grand Total,35,17,1,16,5,25,32,16,3,150

In [33]:
cars.pivot_table(values="price",index="model",columns="color",aggfunc="count",margins=True,margins_name="Grand Total",fill_value=0)

color,Black,Blue,Gold,Gray,Green,Red,Silver,White,Yellow,Grand Total
model,,,,,,,,,,
SE,19,9,1,7,4,12,11,14,1,78
SEL,3,3,0,5,1,2,7,1,1,23
SES,13,5,0,4,0,11,14,1,1,49
Grand Total,35,17,1,16,5,25,32,16,3,150

In [41]:
credit = pd.read_csv('d:/data/credit.csv')
credit.head()

,checking_balance,months_loan_duration,credit_history,purpose,amount,savings_balance,employment_length,installment_rate,personal_status,other_debtors,...,property,age,installment_plan,housing,existing_credits,default,dependents,telephone,foreign_worker,job
0,< 0 DM,6,critical,radio/tv,1169,unknown,> 7 yrs,4,single male,none,...,real estate,67,none,own,2,1,1,yes,yes,skilled employee
1,1 - 200 DM,48,repaid,radio/tv,5951,< 100 DM,1 - 4 yrs,2,female,none,...,real estate,22,none,own,1,2,1,none,yes,skilled employee
2,unknown,12,critical,education,2096,< 100 DM,4 - 7 yrs,2,single male,none,...,real estate,49,none,own,1,1,2,none,yes,unskilled resident
3,< 0 DM,42,repaid,furniture,7882,< 100 DM,4 - 7 yrs,2,single male,guarantor,...,building society savings,45,none,for free,1,1,2,none,yes,skilled employee
4,< 0 DM,24,delayed,car (new),4870,< 100 DM,1 - 4 yrs,3,single male,none,...,unknown/none,53,none,for free,2,2,2,none,yes,skilled employee

In [53]:
credit.pivot_table(values="amount",index="personal_status",columns="purpose",aggfunc="count",fill_value=0,margins=True).transpose()

personal_status      divorced male  female  married male  single male   All
purpose
business                        10      19             9           59    97
car (new)                       10      70            20          134   234
car (used)                       3      24             6           70   103
domestic appliances              1       6             1            4    12
education                        1      21             1           27    50
furniture                       15      74             7           85   181
others                           1       3             0            8    12
radio/tv                         7      85            42          146   280
repairs                          2       5             3           12    22
retraining                       0       3             3            3     9
All                             50     310            92          548  1000

In [65]:
df = credit.pivot_table(values="amount",columns="personal_status",index="purpose",aggfunc="count",fill_value=0,margins=True).transpose()
df

purpose,business,car (new),car (used),domestic appliances,education,furniture,others,radio/tv,repairs,retraining,All
personal_status,,,,,,,,,,,
divorced male,10,10,3,1,1,15,1,7,2,0,50
female,19,70,24,6,21,74,3,85,5,3,310
married male,9,20,6,1,1,7,0,42,3,3,92
single male,59,134,70,4,27,85,8,146,12,3,548
All,97,234,103,12,50,181,12,280,22,9,1000

In [77]:
df.loc[['female'],['education','retraining']]

purpose          education  retraining
personal_status
female                  21           3