In [11]:
import pandas as pd
import numpy as np

In [23]:
iris = pd.read_csv('d:/data/IRIS.csv',header=None,
                   names=['sepal_length','sepal_width','petal_length','petal_width','species'])
iris

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [25]:
iris['new_species'] = iris.species.apply(func=lambda x:x.split("-")[1])
iris.head()

,sepal_length,sepal_width,petal_length,petal_width,species,new_species
0,5.1,3.5,1.4,0.2,Iris-setosa,setosa
1,4.9,3.0,1.4,0.2,Iris-setosa,setosa
2,4.7,3.2,1.3,0.2,Iris-setosa,setosa
3,4.6,3.1,1.5,0.2,Iris-setosa,setosa
4,5.0,3.6,1.4,0.2,Iris-setosa,setosa

In [21]:
insurance = pd.read_csv('d:/data/insurance.csv')
insurance.head()

   age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [27]:
insurance['charges_log10'] = insurance.charges.apply(func=np.log10)
insurance.head()

   age  gender     bmi  children smoker     region      charges  charges_log10
0   19  female  27.900         0    yes  southwest  16884.92400       4.227499
1   18    male  33.770         1     no  southeast   1725.55230       3.236928
2   28    male  33.000         3     no  southeast   4449.46200       3.648308
3   33    male  22.705         0     no  northwest  21984.47061       4.342116
4   32    male  28.880         0     no  northwest   3866.85520       3.587358

In [41]:
insurance['senior_citizen'] = insurance.age.apply(lambda x: 1 if x>=60 else 0)
insurance.head()

,age,gender,bmi,children,smoker,region,charges,charges_log10,senior_citizen
0,19,female,27.900,0,yes,southwest,16884.92400,4.227499,0
1,18,male,33.770,1,no,southeast,1725.55230,3.236928,0
2,28,male,33.000,3,no,southeast,4449.46200,3.648308,0
3,33,male,22.705,0,no,northwest,21984.47061,4.342116,0
4,32,male,28.880,0,no,northwest,3866.85520,3.587358,0

In [43]:
insurance[insurance.senior_citizen==1]

,age,gender,bmi,children,smoker,region,charges,charges_log10,senior_citizen
9,60,female,25.840,0,no,northwest,28923.13692,4.461245,1
11,62,female,26.290,0,yes,southeast,27808.72510,4.444181,1
20,60,female,36.005,0,no,northeast,13228.84695,4.121522,1
26,63,female,23.085,0,no,northeast,14451.83515,4.159923,1
33,63,male,28.310,0,no,northwest,13770.09790,4.138937,1
...,...,...,...,...,...,...,...,...,...
1301,62,male,30.875,3,yes,northwest,46718.16325,4.669486,1
1321,62,male,26.695,0,yes,northeast,28101.33305,4.448727,1
1322,62,male,38.830,0,no,southeast,12981.34570,4.113320,1
1325,61,male,33.535,0,no,northeast,13143.33665,4.118706,1
1337,61,female,29.070,0,yes,northwest,29141.36030,4.464510,1

In [69]:
cars  = pd.read_csv('d:/data/usedcars.csv')
cars.head()

   year model  price  mileage   color transmission
0  2011   SEL  21992     7413  Yellow         AUTO
1  2011   SEL  20995    10926    Gray         AUTO
2  2011   SEL  19995     7351  Silver         AUTO
3  2011   SEL  17809    11613    Gray         AUTO
4  2012    SE  17500     8367   White         AUTO

In [71]:
def convert_price(x):
    if x>=15000:
        return 'high'
    elif x>=10000:
        return 'medium'
    else:
        return 'low'

In [73]:
cars['category']=cars.price.apply(func=convert_price)
cars.head()

   year model  price  mileage   color transmission category
0  2011   SEL  21992     7413  Yellow         AUTO     high
1  2011   SEL  20995    10926    Gray         AUTO     high
2  2011   SEL  19995     7351  Silver         AUTO     high
3  2011   SEL  17809    11613    Gray         AUTO     high
4  2012    SE  17500     8367   White         AUTO     high

In [75]:
cars.category.value_counts()

category
medium    93
high      29
low       28
Name: count, dtype: int64

In [101]:
marks = pd.DataFrame({"maths":[78,82,90,87,90],"physics":[88,85,92,94,85],'chemistry':[90,94,89,88,82]},
                    index=['x','y','z','a','b'])
marks

   maths  physics  chemistry
x     78       88         90
y     82       85         94
z     90       92         89
a     87       94         88
b     90       85         82

In [99]:
marks.apply(func=np.log10,axis=0)

      maths   physics  chemistry
x  1.892095  1.944483   1.954243
y  1.913814  1.929419   1.973128
z  1.954243  1.963788   1.949390
a  1.939519  1.973128   1.944483
b  1.954243  1.929419   1.913814

In [103]:
marks.apply(func=np.sum,axis=0)

maths        427
physics      444
chemistry    443
dtype: int64

In [105]:
marks.apply(func=np.sum,axis=1)

x    256
y    261
z    271
a    269
b    257
dtype: int64

In [109]:
insurance = pd.read_csv('d:/data/insurance.csv')
insurance.head()

   age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [115]:
insurance['risk_category'] =insurance.apply(lambda row: 1 if row.age>=60 and  row.smoker=='yes' else 0 ,axis=1)
insurance.head()

   age  gender     bmi  children smoker     region      charges  risk_category
0   19  female  27.900         0    yes  southwest  16884.92400              0
1   18    male  33.770         1     no  southeast   1725.55230              0
2   28    male  33.000         3     no  southeast   4449.46200              0
3   33    male  22.705         0     no  northwest  21984.47061              0
4   32    male  28.880         0     no  northwest   3866.85520              0

In [135]:
insurance[insurance.risk_category==0].head(40)

,age,gender,bmi,children,smoker,region,charges,risk_category
0,19,female,27.900,0,yes,southwest,16884.92400,0
1,18,male,33.770,1,no,southeast,1725.55230,0
2,28,male,33.000,3,no,southeast,4449.46200,0
3,33,male,22.705,0,no,northwest,21984.47061,0
4,32,male,28.880,0,no,northwest,3866.85520,0
5,31,female,25.740,0,no,southeast,3756.62160,0
6,46,female,33.440,1,no,southeast,8240.58960,0
7,37,female,27.740,3,no,northwest,7281.50560,0
8,37,male,29.830,2,no,northeast,6406.41070,0
9,60,female,25.840,0,no,northwest,28923.13692,0
10,25,female,26.220,0,no,northeast,2721.32080,0
12,23,male,34.400,0,no,southwest,1826.84300,0
13,56,female,39.820,0,no,southeast,11090.71780,0
14,27,male,42.130,0,yes,southeast,39611.75770,0
15,19,female,24.600,1,no,southwest,1837.23700,0
16,52,female,30.780,1,no,northeast,10797.33620,0
17,23,male,23.845,0,no,northeast,2395.17155,0
18,56,male,40.300,0,no,southwest,10602.38500,0
19,30,female,35.300,0,yes,southwest,36837.46700,0
20,60,female,36.005,0,no,northeast,13228.84695,0
21,30,female,32.400,1,no,southwest,4149.73600,0
22,18,male,34.100,0,no,southeast,1137.01100,0
23,34,female,31.920,1,yes,northeast,37701.87680,0
24,37,male,28.025,2,no,northwest,6203.90175,0
25,59,female,27.720,3,no,southeast,14001.13380,0
26,63,female,23.085,0,no,northeast,14451.83515,0
27,55,female,32.775,2,no,northwest,12268.63225,0
28,23,male,17.385,1,no,northwest,2775.19215,0
29,31,male,36.300,2,yes,southwest,38711.00000,0
30,22,male,35.600,0,yes,southwest,35585.57600,0
31,18,female,26.315,0,no,northeast,2198.18985,0
32,19,female,28.600,5,no,southwest,4687.79700,0
33,63,male,28.310,0,no,northwest,13770.09790,0
34,28,male,36.400,1,yes,southwest,51194.55914,0
35,19,male,20.425,0,no,northwest,1625.43375,0
36,62,female,32.965,3,no,northwest,15612.19335,0
37,26,male,20.800,0,no,southwest,2302.30000,0
38,35,male,36.670,1,yes,northeast,39774.27630,0
40,24,female,26.600,0,no,northeast,3046.06200,0
41,31,female,36.630,2,no,southeast,4949.75870,0