In [1]:
import numpy as np 
import pandas as pd

In [8]:
marks = np.random.randint(70,91,(3,5))
marks

array([[75, 89, 89, 76, 89],
       [76, 75, 76, 78, 86],
       [87, 77, 89, 81, 83]])

In [9]:
df = pd.DataFrame(marks,columns=['x','y','z','a','b'],index=['maths','physics','chemistry'])
df.shape

(3, 5)

In [10]:
type(df)

pandas.core.frame.DataFrame

In [44]:
cars= pd.read_csv('c:/data/usedcars.csv',sep=',')
cars.shape

(150, 6)

In [45]:
cars

     year model  price  mileage   color transmission
0    2011   SEL  21992     7413  Yellow         AUTO
1    2011   SEL  20995    10926    Gray         AUTO
2    2011   SEL  19995     7351  Silver         AUTO
3    2011   SEL  17809    11613    Gray         AUTO
4    2012    SE  17500     8367   White         AUTO
..    ...   ...    ...      ...     ...          ...
145  2006   SES   6200    95000  Silver         AUTO
146  2002    SE   5995    87003     Red         AUTO
147  2000    SE   5980    96841     Red         AUTO
148  2001    SE   4899   151479  Yellow         AUTO
149  2000    SE   3800   109259     Red         AUTO

[150 rows x 6 columns]

In [48]:
wine_red = pd.read_csv('c:/data/winequality-red.csv',delimiter=";")
wine_red.shape

(1599, 12)

In [49]:
wine_red

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [57]:
wine_white = pd.read_csv('c:/data/winequality-white.csv',delimiter=";")
wine_white.shape

(4898, 12)

In [58]:
wine_white.shape

(4898, 12)