In [1]:
import pandas as pd

In [3]:
schools = pd.read_csv('c:/data/Districtwise_SchoolData.csv',header=3)
schools

,Statecd,State Name,distcd,distname,ac_year,schgovt1,schgovt2,schgovt3,schgovt4,schgovt5,...,App By Road 4,App By Road 5,App By Road 6,App By Road 7,Scr 30 P,Scr 35 Up,Ptr 30 P,Ptr 35 Up,Avg Instn Days P,Avg Instn Days Up
0,35,ANDAMAN & NICOBAR ISLANDS ...,3501,ANDAMANS ...,2012-13,61,26,19,0.0,5,...,0.0,5.0,18.0,0.0,30.0,18.0,1.0,0.0,215.0,218.0
1,35,ANDAMAN & NICOBAR ISLANDS ...,3503,MIDDLE AND NORTH ANDAMANS ...,2012-13,104,29,5,3.0,8,...,3.0,8.0,10.0,0.0,6.0,3.0,5.0,0.0,215.0,215.0
2,35,ANDAMAN & NICOBAR ISLANDS ...,3502,NICOBARS ...,2012-13,29,11,3,0.0,6,...,0.0,4.0,6.0,0.0,3.0,3.0,0.0,0.0,210.0,212.0
3,28,ANDHRA PRADESH ...,2801,ADILABAD ...,2012-13,3074,440,4,0.0,1,...,0.0,1.0,125.0,689.0,1113.0,457.0,1223.0,244.0,221.0,221.0
4,28,ANDHRA PRADESH ...,2822,ANANTAPUR ...,2012-13,2864,654,23,13.0,495,...,10.0,763.0,3.0,93.0,883.0,407.0,1227.0,271.0,216.0,220.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1319,19,WEST BENGAL ...,1919,PURBA MEDINIPUR ...,2013-14,4727,8,3,445.0,381,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1320,19,WEST BENGAL ...,1914,PURULIYA ...,2013-14,3416,5,4,572.0,246,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1321,19,WEST BENGAL ...,1921,SILIGURI ...,2013-14,687,0,4,41.0,64,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1322,19,WEST BENGAL ...,1918,SOUTH TWENTY FOUR PARGAN ...,2013-14,4970,14,2,362.0,438,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1323,19,WEST BENGAL ...,1904,UTTAR DINAJPUR ...,2013-14,2460,0,1,312.0,145,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
messy = pd.read_csv('c:/data/messydata.csv',sep=' ',skiprows=[0,1,3,6,9],header=0)
messy

,name,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,"Dec,"
0,IBM,156.08,160.01,159.81,165.22,172.25,167.15,164.75,152.77,145.36,146.11,137.21,"137.96,"
1,MSFT,45.51,43.08,42.13,43.47,47.53,45.96,45.61,45.51,43.56,48.70,53.88,"55.40,"
2,GOOGLE,512.42,537.99,559.72,540.50,535.24,532.92,590.09,636.84,617.93,663.59,735.39,"755.35,"
3,APPLE,110.64,125.43,125.97,127.29,128.76,127.81,125.34,113.39,112.80,113.36,118.16,"111.73,"

In [9]:
messy = pd.read_csv('c:/data/messydata.csv',sep=' ',skiprows=2,header=0,comment='@')
messy

,name,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,"Dec,"
0,IBM,156.08,160.01,159.81,165.22,172.25,167.15,164.75,152.77,145.36,146.11,137.21,"137.96,"
1,MSFT,45.51,43.08,42.13,43.47,47.53,45.96,45.61,45.51,43.56,48.70,53.88,"55.40,"
2,GOOGLE,512.42,537.99,559.72,540.50,535.24,532.92,590.09,636.84,617.93,663.59,735.39,"755.35,"
3,APPLE,110.64,125.43,125.97,127.29,128.76,127.81,125.34,113.39,112.80,113.36,118.16,"111.73,"

In [11]:
messy = pd.read_csv('c:/data/messydata.csv',sep=' ',comment='@',header=2)
messy

,name,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,"Dec,"
0,IBM,156.08,160.01,159.81,165.22,172.25,167.15,164.75,152.77,145.36,146.11,137.21,"137.96,"
1,MSFT,45.51,43.08,42.13,43.47,47.53,45.96,45.61,45.51,43.56,48.70,53.88,"55.40,"
2,GOOGLE,512.42,537.99,559.72,540.50,535.24,532.92,590.09,636.84,617.93,663.59,735.39,"755.35,"
3,APPLE,110.64,125.43,125.97,127.29,128.76,127.81,125.34,113.39,112.80,113.36,118.16,"111.73,"

In [34]:
messy = pd.read_csv('c:/data/messydata.csv',sep=' ',skiprows=[3,6],header=2,skipfooter=1,engine='python')
messy

,name,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,"Dec,"
0,IBM,156.08,160.01,159.81,165.22,172.25,167.15,164.75,152.77,145.36,146.11,137.21,"137.96,"
1,MSFT,45.51,43.08,42.13,43.47,47.53,45.96,45.61,45.51,43.56,48.70,53.88,"55.40,"
2,GOOGLE,512.42,537.99,559.72,540.50,535.24,532.92,590.09,636.84,617.93,663.59,735.39,"755.35,"
3,APPLE,110.64,125.43,125.97,127.29,128.76,127.81,125.34,113.39,112.80,113.36,118.16,"111.73,"

In [22]:
airquality = pd.read_csv('c:/data/AirQuality.csv',sep=';',decimal=',',skipfooter=114,engine='python')
airquality

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,10/03/2004,18.00.00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578,NaN,NaN
1,10/03/2004,19.00.00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255,NaN,NaN
2,10/03/2004,20.00.00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502,NaN,NaN
3,10/03/2004,21.00.00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867,NaN,NaN
4,10/03/2004,22.00.00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,04/04/2005,10.00.00,3.1,1314,-200,13.5,1101,472,539,190,1374,1729,21.9,29.3,0.7568,NaN,NaN
9353,04/04/2005,11.00.00,2.4,1163,-200,11.4,1027,353,604,179,1264,1269,24.3,23.7,0.7119,NaN,NaN
9354,04/04/2005,12.00.00,2.4,1142,-200,12.4,1063,293,603,175,1241,1092,26.9,18.3,0.6406,NaN,NaN
9355,04/04/2005,13.00.00,2.1,1003,-200,9.5,961,235,702,156,1041,770,28.3,13.5,0.5139,NaN,NaN
9356,04/04/2005,14.00.00,2.2,1071,-200,11.9,1047,265,654,168,1129,816,28.5,13.1,0.5028,NaN,NaN

In [30]:
cars = pd.read_csv('c:/data/usedcars.csv',nrows=10)
cars

   year model  price  mileage   color transmission
0  2011   SEL  21992     7413  Yellow         AUTO
1  2011   SEL  20995    10926    Gray         AUTO
2  2011   SEL  19995     7351  Silver         AUTO
3  2011   SEL  17809    11613    Gray         AUTO
4  2012    SE  17500     8367   White         AUTO
5  2010   SEL  17495    25125  Silver         AUTO
6  2011   SEL  17000    27393    Blue         AUTO
7  2010   SEL  16995    21026  Silver         AUTO
8  2011   SES  16995    32655  Silver         AUTO
9  2010   SES  16995    36116  Silver         AUTO