In [1]:
import numpy as np 
import pandas as pd

In [2]:
cars = pd.read_csv('c:/data/usedcars.csv')
cars.head()

   year model  price  mileage   color transmission
0  2011   SEL  21992     7413  Yellow         AUTO
1  2011   SEL  20995    10926    Gray         AUTO
2  2011   SEL  19995     7351  Silver         AUTO
3  2011   SEL  17809    11613    Gray         AUTO
4  2012    SE  17500     8367   White         AUTO

In [3]:
cars.price.min(),cars.price.max(),cars.price.mean(),cars.price.median()

(3800, 21992, 12961.933333333332, 13591.5)

In [10]:
cars.price.quantile(q=[0,0.1,0.25,0.4,0.5,0.6,0.75,0.8,0.9,1])

0.00     3800.0
0.10     8431.9
0.25    10995.0
0.40    12993.8
0.50    13591.5
0.60    13992.0
0.75    14904.5
0.80    14999.0
0.90    15999.1
1.00    21992.0
Name: price, dtype: float64

In [6]:
cars[cars.price>13591.5]

    year model  price  mileage   color transmission
0   2011   SEL  21992     7413  Yellow         AUTO
1   2011   SEL  20995    10926    Gray         AUTO
2   2011   SEL  19995     7351  Silver         AUTO
3   2011   SEL  17809    11613    Gray         AUTO
4   2012    SE  17500     8367   White         AUTO
..   ...   ...    ...      ...     ...          ...
70  2009   SES  13799    34888   Black         AUTO
71  2009   SES  13742    38380   Black         AUTO
72  2010   SEL  13687    35574    Gray         AUTO
73  2009   SEL  13663    27528  Silver         AUTO
74  2010   SES  13599    33302     Red         AUTO

[75 rows x 6 columns]

In [7]:
np.min(cars.mileage),np.max(cars.mileage),np.mean(cars.mileage),np.median(cars.mileage)

(4867, 151479, 44260.64666666667, 36385.0)

In [12]:
np.quantile(cars.mileage,q=[0,0.25,0.5,0.75,1])

array([  4867.  ,  27200.25,  36385.  ,  55124.5 , 151479.  ])